from typing import Any, Optional

CONTENT_TYPE_LATEST: str
REGISTRY: Any

def generate_latest(registry: Optional[Any] = ...) -> bytes: ...

def push_to_gateway(*args, **kwargs) -> None: ...

class Counter:
    def __init__(self, name: str, documentation: str, labelnames=..., namespace: str = ..., subsystem: str = ..., unit: str = ...): ...
    def inc(self, amount: float = ...) -> None: ...
    def labels(self, *labelvalues: str) -> "Counter": ...
