import {CHECKPOINT_DEFINITIONS,isCheckpointId,type CheckpointState,type ParserCheckpoint} from '../contracts/checkpoints';
import type {ActionRequired,RunEvent,RunMode,RunOutput,RunState,TerminalStatus} from '../contracts/runtime';
import type {DormantBallotLensSocket} from './socketClient';
export type TrustedRunMode=Exclude<RunMode,'public_registry'>;
export type TrustedSourceSelection=
 |{readonly runMode:'trusted_url'|'worklist';readonly displayLabel:string;readonly url:string}
 |{readonly runMode:'manual_upload';readonly displayLabel:string;readonly uploadPath:string;readonly uploadName:string};
export type TrustedBallotLensSubmitPayload=
 |{readonly trusted_run_mode:'trusted_url'|'worklist';readonly direct_urls:readonly[string]}
 |{readonly trusted_run_mode:'manual_upload';readonly file_source:'uploads';readonly manual_upload_path:string;readonly manual_upload_name:string};
export interface TrustedChoice{readonly displayLabel:string;readonly url:string}
const STATES=new Set<CheckpointState>(['pending','active','complete','warning','error']);
const ACTIONS=new Set<ActionRequired['actionType']>(['contest_selection','vote_method_selection','challenge','other']);
const LABELS=new Map(CHECKPOINT_DEFINITIONS.map(x=>[x.id,x.label]));
const record=(v:unknown):v is Record<string,unknown>=>Boolean(v)&&typeof v==='object'&&!Array.isArray(v);
const req=(v:unknown,f:string)=>{if(typeof v!=='string'||!v.trim())throw new Error(`invalid ${f}`);return v.trim()};
const opt=(v:unknown,f:string)=>v==null?null:req(v,f);
const mode=(v:unknown):TrustedRunMode=>{if(v!=='trusted_url'&&v!=='manual_upload'&&v!=='worklist')throw new Error('invalid run mode');return v};
const http=(v:string)=>{const x=new URL(v.trim());if(!['http:','https:'].includes(x.protocol)||x.username||x.password)throw new Error('invalid URL');return v.trim()};
function checkpoint(v:unknown):ParserCheckpoint{if(!record(v))throw new Error('invalid checkpoint');const id=req(v.checkpoint_id,'checkpoint');if(!isCheckpointId(id))throw new Error('unknown checkpoint');if(!Number.isInteger(v.sequence)||(v.sequence as number)<=0)throw new Error('sequence');if(typeof v.state!=='string'||!STATES.has(v.state as CheckpointState))throw new Error('state');const label=req(v.label,'label');if(LABELS.get(id)!==label)throw new Error('label');if(!Number.isInteger(v.evidence_count)||(v.evidence_count as number)<0)throw new Error('evidence');if(typeof v.requires_action!=='boolean')throw new Error('requires_action');let at:ActionRequired['actionType']|null=null;if(v.action_type!=null){at=req(v.action_type,'action') as ActionRequired['actionType'];if(!ACTIONS.has(at))throw new Error('action')};if(v.requires_action!==(at!==null))throw new Error('action fields');return Object.freeze({checkpointId:id,sequence:v.sequence as number,state:v.state as CheckpointState,label,reasonCode:opt(v.reason_code,'reason'),summary:opt(v.summary,'summary'),evidenceCount:v.evidence_count as number,requiresAction:v.requires_action,actionType:at,updatedAt:opt(v.updated_at,'updated')})}
function action(v:unknown):ActionRequired{if(!record(v))throw new Error('action');const id=req(v.checkpoint_id,'checkpoint');if(!isCheckpointId(id))throw new Error('checkpoint');const at=req(v.action_type,'action') as ActionRequired['actionType'];if(!ACTIONS.has(at))throw new Error('action');return Object.freeze({promptId:req(v.prompt_id,'prompt'),checkpointId:id,actionType:at,summary:req(v.summary,'summary')})}
function counts(v:unknown){if(!record(v))throw new Error('counts');const o:Record<string,number>={};for(const[k,n]of Object.entries(v)){if(!Number.isInteger(n)||(n as number)<0)throw new Error('count');o[k]=n as number}return Object.freeze(o)}
function outputs(v:unknown):readonly RunOutput[]{if(!Array.isArray(v))throw new Error('outputs');return Object.freeze(v.map(raw=>{if(!record(raw)||raw.persistence!=='persisted'||typeof raw.download_available!=='boolean')throw new Error('output');return Object.freeze({outputId:req(raw.output_id,'output id'),label:req(raw.label,'label'),persistence:'persisted' as const,downloadAvailable:raw.download_available})}))}
const terminal=(v:unknown):TerminalStatus=>{if(v!=='success'&&v!=='completed_with_errors'&&v!=='failed'&&v!=='cancelled')throw new Error('terminal');return v};
export function buildTrustedSubmitPayload(s:TrustedSourceSelection):TrustedBallotLensSubmitPayload{if(s.runMode==='manual_upload'){const p=s.uploadPath.trim().replace(/\\/g,'/'),n=s.uploadName.trim();if(!p||!n)throw new Error('upload required');return Object.freeze({trusted_run_mode:'manual_upload' as const,file_source:'uploads' as const,manual_upload_path:p,manual_upload_name:n})}return Object.freeze({trusted_run_mode:s.runMode,direct_urls:Object.freeze([http(s.url)]) as readonly[string]})}
export function submitTrustedSource(socket:DormantBallotLensSocket,s:TrustedSourceSelection){socket.connect();socket.emit('ballot_lens',buildTrustedSubmitPayload(s))}
function urls(raw:unknown){const a=Array.isArray(raw)?raw:record(raw)&&Array.isArray(raw.urls)?raw.urls:[];const out:string[]=[];for(const e of a){const c=typeof e==='string'?e:record(e)&&typeof e.url==='string'?e.url:record(e)&&typeof e.source_url==='string'?e.source_url:'';if(c)try{const u=http(c);if(!out.includes(u))out.push(u)}catch{/* backend is final authority */}}return Object.freeze(out)}
export async function fetchTrustedUrlLibrary():Promise<readonly TrustedChoice[]>{const r=await fetch('/api/urls',{method:'GET',credentials:'same-origin',headers:{Accept:'application/json'}});if(!r.ok)throw new Error('URL Library unavailable');return Object.freeze(urls(await r.json()).map(url=>Object.freeze({displayLabel:url,url})))}
export async function fetchTrustedWorklist():Promise<readonly TrustedChoice[]>{const r=await fetch('/api/election_data/worklist/overview?limit=200',{method:'GET',credentials:'same-origin',headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Worklist unavailable');const j:unknown=await r.json();const a=record(j)?[j.items,j.rows,j.worklist,j.data].find(Array.isArray)??[]:[];return Object.freeze(urls(a).map(url=>Object.freeze({displayLabel:url,url})))}
function owns(st:RunState,s:TrustedSourceSelection|null){return Boolean(s&&st.context.runMode===s.runMode&&st.context.sourceSummary?.runMode===s.runMode&&st.context.sourceSummary?.displayLabel===s.displayLabel)}
export function routeTrustedLifecycleEvent(name:'session_id'|'parser_output'|'trusted_ballot_lens_result',payload:unknown,st:RunState,s:TrustedSourceSelection|null,at:string):RunEvent|null{if(!owns(st,s)||!s)return null;if(name==='session_id'){if(!record(payload)||!['submitting','awaiting_session'].includes(st.status)||st.context.sessionId!==null)return null;return Object.freeze({type:'SESSION_CORRELATED' as const,runMode:s.runMode,sessionId:req(payload.session_id,'session'),startedAt:at})}if(name==='trusted_ballot_lens_result'){if(!record(payload)||payload.contract!=='ballot_lens_trusted_runtime_result_v1')throw new Error('result contract');const sid=req(payload.session_id,'session'),rm=mode(payload.run_mode);if(!['running','disconnected'].includes(st.status)||st.context.sessionId!==sid||rm!==s.runMode)return null;return Object.freeze({type:'RUN_TERMINATED' as const,sessionId:sid,terminalStatus:terminal(payload.terminal_status),terminalReasonCode:opt(payload.terminal_reason_code,'reason'),statusCounts:counts(payload.status_counts),outputs:outputs(payload.outputs),completedAt:at})}if(!record(payload)||st.status!=='running'||!st.context.sessionId||payload.session_id!==st.context.sessionId||payload.run_mode!==s.runMode)return null;if(payload.reason_code==='trusted_runtime_checkpoint_updated')return Object.freeze({type:'CHECKPOINT_UPDATED' as const,sessionId:st.context.sessionId,checkpoint:checkpoint(payload.checkpoint)});if(payload.reason_code==='trusted_runtime_action_required')return Object.freeze({type:'ACTION_REQUIRED' as const,sessionId:st.context.sessionId,action:action(payload.action)});if(payload.reason_code==='trusted_runtime_action_resolved')return Object.freeze({type:'ACTION_RESOLVED' as const,sessionId:st.context.sessionId,promptId:req(payload.prompt_id,'prompt')});return null}
export function installTrustedRuntimeLifecycle(socket:DormantBallotLensSocket,o:{getRunState:()=>RunState;getSelection:()=>TrustedSourceSelection|null;dispatch:(e:RunEvent)=>void;onProtocolError:()=>void;now?:()=>string}){const now=o.now??(()=>new Date().toISOString()),names=['session_id','parser_output','trusted_ballot_lens_result'] as const,listeners=new Map<string,(p?:unknown)=>void>();for(const n of names){const l=(p?:unknown)=>{try{const e=routeTrustedLifecycleEvent(n,p,o.getRunState(),o.getSelection(),now());if(e)o.dispatch(e)}catch{o.onProtocolError()}};listeners.set(n,l);socket.on(n,l)}return()=>{for(const[n,l]of listeners)socket.off(n,l)}}
