import {useEffect,useState} from 'react';
import type {RunMode} from '../../contracts/runtime';
import {fetchTrustedUrlLibrary,fetchTrustedWorklist,type TrustedChoice,type TrustedSourceSelection} from '../../services/trustedExecution';
export function TrustedSourceBrowser({activeMode,uploadedFiles,selectionLocked,selected,onSelectionChange}:{activeMode:Exclude<RunMode,'public_registry'>;uploadedFiles:readonly string[];selectionLocked:boolean;selected:TrustedSourceSelection|null;onSelectionChange:(s:TrustedSourceSelection|null)=>void}){
 const[choices,setChoices]=useState<readonly TrustedChoice[]>([]),[error,setError]=useState<string|null>(null);
 useEffect(()=>{let off=false;setChoices([]);setError(null);if(activeMode==='manual_upload')return()=>{off=true};const load=activeMode==='worklist'?fetchTrustedWorklist:fetchTrustedUrlLibrary;load().then(x=>{if(!off)setChoices(x)}).catch(()=>{if(!off)setError('Trusted source list unavailable.')});return()=>{off=true}},[activeMode]);
 const value=selected?.runMode===activeMode?(selected.runMode==='manual_upload'?selected.uploadPath:selected.url):'';
 if(activeMode==='manual_upload')return <section className="blf2-registry" aria-label="Trusted uploads"><form method="post" action="/ballot_lens" encType="multipart/form-data"><label>Upload a new artifact<input type="file" name="data_file" disabled={selectionLocked}/></label><button type="submit" disabled={selectionLocked}>Upload with existing trusted gate</button></form><label>Select an uploaded file<select value={value} disabled={selectionLocked} onChange={e=>{const p=e.currentTarget.value;if(!p)return onSelectionChange(null);const n=p.split('/').pop()??p;onSelectionChange(Object.freeze({runMode:'manual_upload' as const,displayLabel:n,uploadPath:p,uploadName:n}))}}><option value="">Choose existing upload</option>{uploadedFiles.map(p=><option key={p} value={p}>{p}</option>)}</select></label></section>;
 return <section className="blf2-registry" aria-label={activeMode==='worklist'?'Governed Worklist':'Approved trusted URL Library'}><h3>{activeMode==='worklist'?'Governed Worklist':'Approved URL Library'}</h3><span className="blf2-panel-state">Backend registry gate remains authoritative</span>{error&&<p role="alert">{error}</p>}<label>Select an existing reviewed target<select value={value} disabled={selectionLocked} onChange={e=>{const u=e.currentTarget.value,c=choices.find(x=>x.url===u);if(!c)return onSelectionChange(null);onSelectionChange(Object.freeze({runMode:activeMode,displayLabel:c.displayLabel,url:c.url}))}}><option value="">Choose reviewed target</option>{choices.map(c=><option key={c.url} value={c.url}>{c.displayLabel}</option>)}</select></label><p>Selection is not authorization; backend reviewed-registry and guarded-ingestion checks remain final.</p></section>}
