"""Initial schema: election data models

Revision ID: a2305f825683
Revises: 
Create Date: 2026-03-29 19:46:30.611897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2305f825683'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_metadata',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'ERROR', name='statusenum'), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('data_framework_preview_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('mode', sa.String(length=24), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('contest', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_framework_preview_cache_expires_at'), 'data_framework_preview_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_data_framework_preview_cache_mode'), 'data_framework_preview_cache', ['mode'], unique=False)
    op.create_index(op.f('ix_data_framework_preview_cache_session_id'), 'data_framework_preview_cache', ['session_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('segment_hash', sa.String(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('segment_hash')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('misc_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('type_', sa.String(), nullable=False),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('FEDERAL', 'STATE', 'COUNTY', 'LOCAL', name='officelevelenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offices_level'), 'offices', ['level'], unique=False)
    op.create_index(op.f('ix_offices_name'), 'offices', ['name'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=True)
    op.create_table('table_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest', sa.String(), nullable=False),
    sa.Column('headers', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_structures_contest'), 'table_structures', ['contest'], unique=False)
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'state_id', name='_county_state_uc')
    )
    op.create_index(op.f('ix_counties_name'), 'counties', ['name'], unique=False)
    op.create_index(op.f('ix_counties_state_id'), 'counties', ['state_id'], unique=False)
    op.create_table('staging_election_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'ERROR', name='statusenum'), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_metadata.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_election_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('contest', sa.String(), nullable=True),
    sa.Column('candidate', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('precinct', sa.String(), nullable=True),
    sa.Column('election_date', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('verification_status', sa.String(length=16), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_principal', sa.String(length=256), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=256), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_metadata.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_', sa.String(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_name'), 'candidates', ['name'], unique=False)
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('election_types', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('type_', sa.String(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'year', 'type_', 'state_id', 'county_id', name='_contest_uc')
    )
    op.create_index('ix_contest_year', 'contests', ['title', 'year'], unique=False)
    op.create_index(op.f('ix_contests_county_id'), 'contests', ['county_id'], unique=False)
    op.create_index(op.f('ix_contests_state_id'), 'contests', ['state_id'], unique=False)
    op.create_index(op.f('ix_contests_title'), 'contests', ['title'], unique=False)
    op.create_index(op.f('ix_contests_year'), 'contests', ['year'], unique=False)
    op.create_table('ballot_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ballot_types_text', sa.Text(), nullable=False),
    sa.Column('ballot_types_html', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('type_', sa.String(), nullable=True),
    sa.Column('segment_hash', sa.String(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ballot_types_ballot_types_text'), 'ballot_types', ['ballot_types_text'], unique=False)
    op.create_index(op.f('ix_ballot_types_segment_hash'), 'ballot_types', ['segment_hash'], unique=False)
    op.create_index(op.f('ix_ballot_types_year'), 'ballot_types', ['year'], unique=False)
    op.create_table('buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('selector', sa.String(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('is_clickable', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_panel_text', sa.Text(), nullable=False),
    sa.Column('candidate_panel_html', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('type_', sa.String(), nullable=True),
    sa.Column('segment_hash', sa.String(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_panels_candidate_panel_text'), 'candidate_panels', ['candidate_panel_text'], unique=False)
    op.create_index(op.f('ix_candidate_panels_segment_hash'), 'candidate_panels', ['segment_hash'], unique=False)
    op.create_index(op.f('ix_candidate_panels_year'), 'candidate_panels', ['year'], unique=False)
    op.create_table('headings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading_text', sa.Text(), nullable=False),
    sa.Column('heading_html', sa.Text(), nullable=True),
    sa.Column('heading_type', sa.String(), nullable=True),
    sa.Column('segment_hash', sa.String(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_headings_heading_text'), 'headings', ['heading_text'], unique=False)
    op.create_index(op.f('ix_headings_segment_hash'), 'headings', ['segment_hash'], unique=False)
    op.create_table('location_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_panel_text', sa.Text(), nullable=False),
    sa.Column('location_panel_html', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('type_', sa.String(), nullable=True),
    sa.Column('segment_hash', sa.String(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_panels_location_panel_text'), 'location_panels', ['location_panel_text'], unique=False)
    op.create_index(op.f('ix_location_panels_segment_hash'), 'location_panels', ['segment_hash'], unique=False)
    op.create_index(op.f('ix_location_panels_year'), 'location_panels', ['year'], unique=False)
    op.create_table('panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_text', sa.Text(), nullable=False),
    sa.Column('panel_html', sa.Text(), nullable=True),
    sa.Column('segment_hash', sa.String(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panels_panel_text'), 'panels', ['panel_text'], unique=False)
    op.create_index(op.f('ix_panels_segment_hash'), 'panels', ['segment_hash'], unique=False)
    op.create_table('party_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_label_text', sa.Text(), nullable=False),
    sa.Column('party_label_html', sa.Text(), nullable=True),
    sa.Column('segment_hash', sa.String(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_labels_party_label_text'), 'party_labels', ['party_label_text'], unique=False)
    op.create_index(op.f('ix_party_labels_segment_hash'), 'party_labels', ['segment_hash'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('is_incumbent', sa.Boolean(), nullable=True),
    sa.Column('vote_method', sa.String(), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results_timestamps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp_text', sa.Text(), nullable=False),
    sa.Column('timestamp_html', sa.Text(), nullable=True),
    sa.Column('segment_hash', sa.String(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_timestamps_segment_hash'), 'results_timestamps', ['segment_hash'], unique=False)
    op.create_index(op.f('ix_results_timestamps_timestamp_text'), 'results_timestamps', ['timestamp_text'], unique=False)
    op.create_table('vote_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_method_text', sa.Text(), nullable=False),
    sa.Column('vote_method_html', sa.Text(), nullable=True),
    sa.Column('segment_hash', sa.String(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metastats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_methods_segment_hash'), 'vote_methods', ['segment_hash'], unique=False)
    op.create_index(op.f('ix_vote_methods_vote_method_text'), 'vote_methods', ['vote_method_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_methods_vote_method_text'), table_name='vote_methods')
    op.drop_index(op.f('ix_vote_methods_segment_hash'), table_name='vote_methods')
    op.drop_table('vote_methods')
    op.drop_index(op.f('ix_results_timestamps_timestamp_text'), table_name='results_timestamps')
    op.drop_index(op.f('ix_results_timestamps_segment_hash'), table_name='results_timestamps')
    op.drop_table('results_timestamps')
    op.drop_table('results')
    op.drop_index(op.f('ix_party_labels_segment_hash'), table_name='party_labels')
    op.drop_index(op.f('ix_party_labels_party_label_text'), table_name='party_labels')
    op.drop_table('party_labels')
    op.drop_index(op.f('ix_panels_segment_hash'), table_name='panels')
    op.drop_index(op.f('ix_panels_panel_text'), table_name='panels')
    op.drop_table('panels')
    op.drop_index(op.f('ix_location_panels_year'), table_name='location_panels')
    op.drop_index(op.f('ix_location_panels_segment_hash'), table_name='location_panels')
    op.drop_index(op.f('ix_location_panels_location_panel_text'), table_name='location_panels')
    op.drop_table('location_panels')
    op.drop_index(op.f('ix_headings_segment_hash'), table_name='headings')
    op.drop_index(op.f('ix_headings_heading_text'), table_name='headings')
    op.drop_table('headings')
    op.drop_index(op.f('ix_candidate_panels_year'), table_name='candidate_panels')
    op.drop_index(op.f('ix_candidate_panels_segment_hash'), table_name='candidate_panels')
    op.drop_index(op.f('ix_candidate_panels_candidate_panel_text'), table_name='candidate_panels')
    op.drop_table('candidate_panels')
    op.drop_table('buttons')
    op.drop_index(op.f('ix_ballot_types_year'), table_name='ballot_types')
    op.drop_index(op.f('ix_ballot_types_segment_hash'), table_name='ballot_types')
    op.drop_index(op.f('ix_ballot_types_ballot_types_text'), table_name='ballot_types')
    op.drop_table('ballot_types')
    op.drop_index(op.f('ix_contests_year'), table_name='contests')
    op.drop_index(op.f('ix_contests_title'), table_name='contests')
    op.drop_index(op.f('ix_contests_state_id'), table_name='contests')
    op.drop_index(op.f('ix_contests_county_id'), table_name='contests')
    op.drop_index('ix_contest_year', table_name='contests')
    op.drop_table('contests')
    op.drop_index(op.f('ix_candidates_name'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('districts')
    op.drop_table('warehouse_election_results')
    op.drop_table('staging_election_results')
    op.drop_index(op.f('ix_counties_state_id'), table_name='counties')
    op.drop_index(op.f('ix_counties_name'), table_name='counties')
    op.drop_table('counties')
    op.drop_index(op.f('ix_table_structures_contest'), table_name='table_structures')
    op.drop_table('table_structures')
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.drop_table('states')
    op.drop_table('parties')
    op.drop_index(op.f('ix_offices_name'), table_name='offices')
    op.drop_index(op.f('ix_offices_level'), table_name='offices')
    op.drop_table('offices')
    op.drop_table('misc_entities')
    op.drop_table('entities')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_data_framework_preview_cache_session_id'), table_name='data_framework_preview_cache')
    op.drop_index(op.f('ix_data_framework_preview_cache_mode'), table_name='data_framework_preview_cache')
    op.drop_index(op.f('ix_data_framework_preview_cache_expires_at'), table_name='data_framework_preview_cache')
    op.drop_table('data_framework_preview_cache')
    op.drop_table('batch_metadata')
    op.drop_table('alerts')
    # ### end Alembic commands ###
